version: "3.8"

services:
  nodejs:
    container_name: wiseboq_puppeteer
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "${PORT}:${PORT}"
    networks:
      - puppeteer-network

networks:
  puppeteer-network:
    name: puppeteer-network
