version: "3.0"

services:
  nodejs:
    container_name: wiseboq-puppeteer
    build:
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    platform: linux/x86_64
    networks:
      - puppeteer-network

networks:
  puppeteer-network:
    name: puppeteer-network
